server:
  port: 9191
  address: 0.0.0.0
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: authorization-server
  datasource:
    url: jdbc:mysql://localhost:3344/authDB?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1