server:
  port: 8031
  address: 0.0.0.0
spring:
  zipkin:
    base-url: http//:localhost:9411
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3344/orderdb
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9191
      client:
        client-id: mobile
        client-secret: pin
hibernate:
  dialect:
    storage_engine: innodb

gateway:
  port: 8080
  address: 127.0.0.1

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1

