server:
  port: 8041
  address: 0.0.0.0
spring:
  zipkin:
    base-url: http://127.0.0.1:9411
  application:
    name: pdf-generator
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3344/orderdb
    username: root
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9191/zipkin
      client:
        client-id: mobile
        client-secret: pin

pdf:
  directory: pdf/

gateway:
  port: 8080
  address: localhost
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
